const { S3Client, PutObjectCommand, GetObjectCommand, HeadObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');
const crypto = require('crypto');
const env = require('../config/env');

const ALLOWED_CONTENT_TYPES = Object.freeze({
  'image/jpeg': 'jpg',
  'image/png': 'png'
});

const PRESIGNED_URL_EXPIRES_IN_SECONDS = 300; // 5 minutes
const MAX_PHOTO_SIZE_BYTES = 3 * 1024 * 1024; // 3 MB (SPEC.md Section 9)

// Initialize S3Client with AWS SDK v3 credential chain (EC2 IAM role / local env)
let s3Client = new S3Client({
  region: env.AWS_REGION
});

/**
 * For testing purposes: allows injecting a custom or mock S3Client.
 * @param {object} client
 */
function setS3Client(client) {
  s3Client = client;
}

/**
 * For testing purposes: allows retrieving the current S3Client.
 * @returns {S3Client}
 */
function getS3Client() {
  return s3Client;
}

/**
 * Generates a presigned S3 PUT URL for direct client-to-S3 upload.
 * Security & SPEC rules:
 * - Bucket remains private; no public-read ACL is specified.
 * - S3 key is strictly generated by backend under the 'devices/' prefix.
 * - Allowed content types: image/jpeg, image/png only.
 * - Expiration: exactly 300 seconds (5 minutes).
 *
 * @param {object} params
 * @param {string} params.contentType
 * @returns {Promise<{ uploadUrl: string, key: string }>}
 */
async function createUploadPresignedUrl({ contentType }) {
  if (!contentType || !ALLOWED_CONTENT_TYPES[contentType]) {
    const error = new Error('Invalid content type. Allowed types: image/jpeg, image/png');
    error.statusCode = 400;
    throw error;
  }

  const extension = ALLOWED_CONTENT_TYPES[contentType];
  const uniqueId = crypto.randomUUID();
  const key = `devices/${uniqueId}.${extension}`;

  const command = new PutObjectCommand({
    Bucket: env.S3_BUCKET_NAME,
    Key: key,
    ContentType: contentType
  });

  const uploadUrl = await getSignedUrl(s3Client, command, {
    expiresIn: PRESIGNED_URL_EXPIRES_IN_SECONDS
  });

  return {
    uploadUrl,
    key
  };
}

/**
 * Generates a short-lived presigned S3 GET URL for viewing private photos.
 * Reusable helper per SPEC.md Section 5 & 8.
 *
 * @param {object} params
 * @param {string} params.key
 * @param {number} [params.expiresIn=300]
 * @returns {Promise<string>}
 */
async function createDownloadPresignedUrl({ key, expiresIn = PRESIGNED_URL_EXPIRES_IN_SECONDS }) {
  if (!key || typeof key !== 'string' || !key.startsWith('devices/')) {
    const error = new Error('Invalid S3 object key');
    error.statusCode = 400;
    throw error;
  }

  const command = new GetObjectCommand({
    Bucket: env.S3_BUCKET_NAME,
    Key: key
  });

  return getSignedUrl(s3Client, command, {
    expiresIn
  });
}

/**
 * Verifies that the uploaded photo exists in S3, belongs to the devices/ prefix,
 * has an allowed MIME type, and does not exceed the maximum allowed size (3 MB).
 *
 * @param {object} params
 * @param {string} params.key
 * @returns {Promise<{ contentLength: number, contentType: string }>}
 */
async function verifyDevicePhotoObject({ key }) {
  if (!key || typeof key !== 'string' || !/^devices\/[0-9a-f-]{36}\.(jpe?g|png)$/i.test(key)) {
    const error = new Error('Invalid photoKey format. Key must be inside the devices/ namespace');
    error.statusCode = 400;
    throw error;
  }

  try {
    const command = new HeadObjectCommand({
      Bucket: env.S3_BUCKET_NAME,
      Key: key
    });

    const response = await s3Client.send(command);

    const contentType = response.ContentType || '';
    if (!['image/jpeg', 'image/png'].includes(contentType)) {
      const error = new Error('Invalid S3 object content type. Only JPEG and PNG are allowed');
      error.statusCode = 400;
      throw error;
    }

    const contentLength = response.ContentLength || 0;
    if (contentLength > MAX_PHOTO_SIZE_BYTES) {
      const error = new Error('Uploaded photo exceeds maximum allowed size of 3 MB');
      error.statusCode = 400;
      throw error;
    }

    return {
      contentLength,
      contentType
    };
  } catch (err) {
    if (err.statusCode) {
      throw err;
    }
    if (err.name === 'NotFound' || err.name === 'NoSuchKey' || err.$metadata?.httpStatusCode === 404) {
      const error = new Error('Uploaded photo object does not exist in S3 storage');
      error.statusCode = 400;
      throw error;
    }
    const error = new Error('Failed to verify photo in storage');
    error.statusCode = 400;
    throw error;
  }
}

/**
 * Retrieves the raw photo bytes and content type from S3 for Bedrock Converse API ingestion.
 *
 * @param {object} params
 * @param {string} params.key
 * @returns {Promise<{ bytes: Uint8Array, format: 'jpeg' | 'png' }>}
 */
async function getPhotoBytes({ key }) {
  const command = new GetObjectCommand({
    Bucket: env.S3_BUCKET_NAME,
    Key: key
  });

  const response = await s3Client.send(command);

  let bytes;
  if (response.Body?.transformToByteArray) {
    bytes = await response.Body.transformToByteArray();
  } else if (response.Body && typeof response.Body.on === 'function') {
    // Stream fallback
    const chunks = [];
    for await (const chunk of response.Body) {
      chunks.push(chunk);
    }
    bytes = new Uint8Array(Buffer.concat(chunks));
  } else if (Buffer.isBuffer(response.Body)) {
    bytes = new Uint8Array(response.Body);
  } else {
    bytes = new Uint8Array(0);
  }

  const format = key.toLowerCase().endsWith('.png') ? 'png' : 'jpeg';

  return {
    bytes,
    format
  };
}

module.exports = {
  createUploadPresignedUrl,
  createDownloadPresignedUrl,
  verifyDevicePhotoObject,
  getPhotoBytes,
  setS3Client,
  getS3Client,
  ALLOWED_CONTENT_TYPES,
  PRESIGNED_URL_EXPIRES_IN_SECONDS,
  MAX_PHOTO_SIZE_BYTES
};
